### ISSUE TITLE
[GAME BUG] - Slam 'n Jam 96 graphical glitches when using latest loader 20200611

### ISSUE THREAD

**Issue by brNX** [AppCakeLtd/fenrir-bug-reports#1] opened 2020-06-15 18:39 UTC
**Game Name**
Slam 'n Jam '96 featuring Magic & Kareem - Signature Edition

**Game Region**
US

**Game Source**
- [x] Redump (cue/bin)
- [ ] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Describe the bug**
Sprite glitches in the menu just before the tip-off and after the tip-off, the same doesn't happen using a older launcher (20200520  V: 4e28c41)

**Console Revision**
- [x] VA0
- [ ] VA0.5
- [ ] VA0.8
- [ ] VA1

**Console Region**
- [x] PAL
- [ ] NTSC-U
- [ ] NTSC-J
- [ ] Other

**Firmware and Loader Version**
- Firmware Version: 6cdf9cc3
- Loader Version: 2afdf05

**Cartridge Attached**
- [x] None
- [ ] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
1. Launch Game and start an exhibition game by pressing start a few times
2. Graphical Glitches appear on the menu before going in-game and after the tip-off

**Flex Cable Attached**
- [ ] Original Flex Cable
- [x] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
No glitches visible(see second screenshot)

**Screenshots / Photos**
with fenrir.iso from 20200611:
![image](https://user-images.githubusercontent.com/407195/84692254-7a6c3880-af3d-11ea-818e-6d662b8ed55f.png)
with fenrir.iso from 20200520 (before direct boot):
![image (1)](https://user-images.githubusercontent.com/407195/84693274-22cecc80-af3f-11ea-9f81-e0167dfb1dcf.png)

**Additional context**
EU VA0 modded to 60Hz

**Comment by ThanosSiopoudis** [comment] 2020-06-15 18:55
@brNX Thanks for reporting this. Can you please let us know if the bug is resolved by launching the game using option "B" in Loader?

**Comment by brNX** [comment] 2020-06-15 19:02
Hi 
I must be blind, I completely missed that option, yes it's working fine using "B" (CD player)

**Comment by ThanosSiopoudis** [comment] 2020-06-15 20:13
Ok, thanks.
@Ced2911 This is a DirectBoot issue

**Comment by loukas599** [comment] 2020-06-23 12:31
i have the same problem with Pseudo Saturn All in One cart please help

**Comment by ThanosSiopoudis** [comment] 2020-06-23 13:21
Did you try what was suggested above?

**Comment by loukas599** [comment] 2020-06-23 13:45
I can't find option b

**Comment by ThanosSiopoudis** [comment] 2020-06-23 13:46
Do you see option "C"? If not, then either your cartridge is not properly seated, or you are on an older version firmware / loader

**Comment by loukas599** [comment] 2020-06-23 13:59
I pressed something at the settings and now nothing working. stuck at this screen @ #
![15929207671957556774827068956648](https://user-images.githubusercontent.com/67323263/85413018-eddffc80-b572-11ea-8308-e4b1ea29c375.jpg)

**Comment by ThanosSiopoudis** [comment] 2020-06-23 14:02
Please get in touch via email for technical support, this is for reporting game bugs only.

**Comment by loukas599** [comment] 2020-06-23 14:04
Ok i fix it 😁
Can you tell me where is the c option;
@
![15929210275448634953661254022400](https://user-images.githubusercontent.com/67323263/85413465-870f1300-b573-11ea-92a7-199f3da466d8.jpg)

**Comment by ThanosSiopoudis** [comment] 2020-06-23 14:38
The "C" option is in Fenrir loader. Just launch in Pseudo, you'll end up in Loader. Then choose a game and press "C".

**Comment by loukas599** [comment] 2020-06-23 15:26
So it's not supported (i have only the red cartridge)
Thank you

**Comment by ThanosSiopoudis** [comment] 2020-08-02 19:26
It looks like the game doesn't like DirectBoot and possibly can't be fixed for it. The issue is reproducible with a disc and PseudoKai (no Fenrir) so I'm closing the ticket for now.
Workaround is to use option "B" without an AR / Pseudo Kai cart, or option "C" with an AR / Pseudo Kai cart.

**Closed by ThanosSiopoudis** 2020-08-02 19:26 UTC
Labels: Awaiting Confirmation, Bug, DirectBoot
