### ISSUE TITLE
[FW Bug] Audio distortion from Left Audio Channel on VA1 consoles

### ISSUE THREAD

**Issue by ilpappa** [AppCakeLtd/fenrir-bug-reports#9] opened 2020-07-26 22:20 UTC
*IMPORTANT*
Please only use this page to report compatibility issues with Fenrir. If you are looking for generic support, please contact hello@8bitmods.com

**Game Name**
Die Hard Arcade, Sonic 3D, Virtual Open Tennis

**Game Region**
Die Hard Araced PAL and USA, PAL for the rest

**Game Source**
- [X] Redump (cue/bin)
- [ ] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Describe the bug**
Game has cracking audio on Left audio channel (white plug) that come and go on power cycles. PAL and USA versions tested and both affected.

**Console Revision**
If you don't know the revision of your console, please leave blank
- [ ] VA0
- [ ] VA0.5
- [ ] VA0.8
- [X] VA1

**Console Region**
- [X] PAL
- [ ] NTSC-U
- [ ] NTSC-J
- [ ] Other

**Firmware and Loader Version**
To check your firmware and loader version, go to the Options in the Loader app (Start button). The text next to "FW" is your board's firmware, and the text next to "V" is the Loader version.
- Firmware Version: da719d1b
- Loader Version: 2020/07/22

**Cartridge Attached**
(Please select more than one if it applies)
- [X] None
- [ ] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
1. Direct lauch of the game from game list

**Flex Cable Attached**
- [ ] Original Flex Cable
- [X] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
No cracking audio

**Screenshots / Photos**
NA

**Additional context**
Saturn has its original PSU. Transcendt 64gb micro sd used (TS64GUSDU1)

**Comment by privateye** [comment] 2020-07-30 23:46
I have not been able to re-produce these issues in:
-  Die Hard Arcade (USA)
- Sonic 3D Blast (USA)

Sonic 3D - Flickies' Island (Europe) is inferior to the NTSC versions since the the 3D bonus stages don’t work at 60Hz. Therefore, I didn't bother testing it. This is my configuration:

**Game Source**
- [x] Redump (cue/bin)
- [ ] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Console Revision**
- [ ] VA0
- [x] VA0.5
- [ ] VA0.8
- [ ] VA1

**Console Region**
- [ ] PAL
- [ ] NTSC-U
- [x] NTSC-J
- [ ] Other

**Firmware and Loader Version**
- Firmware Version: da719d1b
- Loader Version: 951db30

**Cartridge Attached**
(Please select more than one if it applies)
- [ ] None
- [ ] Action Replay 3 in 1
- [x] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [x] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**Flex Cable Attached**
- [x] Original Flex Cable
- [ ] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Additional context**
Games installed on SanDisk Ultra 128 GB microSDXC card, formatted with Panasonic SD Card Formatter 5.0.1.

**Comment by Aergan** [comment] 2020-08-01 14:16
Also having this issue with various games on a VA1 (PAL) at 60Hz.

**Game Name**
Daytona USA (PAL), Daytona USA Circuit Edition (NTSC-U), Sonic Jam (NTSC-U), Nights into Dreams (PAL), Nights into Dreams (NTSC-J), Xmas Nights into Dreams (NTSC-U), Xmas Nights into Dreams (NTSC-J), Road Rash (NTSC-U), Panzer Dragoon (PAL), Sonic R (NTSC-J), Thunder Force V (NTSC-J).

**Game Region**
Mixed @ 60Hz operation

**Game Source**
- [x] Redump (cue/bin)
- [x] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [x] Other (ccd/img)

**Describe the bug**
Audio distortion & clipping. Affects left channel only, sometimes intermittent unless moving back to 2020/03/29 (dev) firmware where it affects both channels in every game, every time. Does not affect CDDA via the CD Player.

**Console Revision**
If you don't know the revision of your console, please leave blank
- [ ] VA0
- [ ] VA0.5
- [ ] VA0.8
- [x] VA1

**Console Region**
- [x] PAL
- [ ] NTSC-U
- [ ] NTSC-J
- [x] Other

**Firmware and Loader Version**
To check your firmware and loader version, go to the Options in the Loader app (Start button). The text next to "FW" is your board's firmware, and the text next to "V" is the Loader version.
- Firmware Version: da719d1b
- Loader Version: 951db30

**Cartridge Attached**
(Please select more than one if it applies)
- [ ] None
- [ ] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch affected game
2. Audio issue immediately occurs or on reset if not.

**Flex Cable Attached**
- [ ] Original Flex Cable
- [x] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
Loading same games from disc with original drive does not have this issue.

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

**Additional context**
Information supplied to 8bitmods via Twitter DM.
Console and PSU fully serviced on main system. Tested on untouched / factory system (spare, identical board revision) and was able to reproduce.

**Comment by ThanosSiopoudis** [comment] 2020-08-02 19:20
This is confirmed, and unrelated to the games themselves. There is a bug with VA1s and the left audio channel. @Ced2911 is working on a fix

**Comment by ThanosSiopoudis** [comment] 2020-08-23 17:49
Fixed in latest FW (https://www.fenrir-ode.fr/firmware.html#download)

**Closed by ThanosSiopoudis** 2020-08-23 17:49 UTC
Labels: Able to Reproduce, Bug
