### ISSUE TITLE
Salamander Deluxe Pack [GAME BUG]

### ISSUE THREAD

**Issue by jpipes** [AppCakeLtd/fenrir-bug-reports#7] opened 2020-06-26 01:46 UTC
*IMPORTANT*
Please only use this page to report compatibility issues with Fenrir. If you are looking for generic support, please contact hello@8bitmods.com

**Game Name**
Salamander Deluxe Pack
**Game Region**
Japan
**Game Source**
- [x] Redump (cue/bin)
- [ ] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Describe the bug**
A clear and concise description of what happens when you attempt to launch, or when you play the game.

**Console Revision**
If you don't know the revision of your console, please leave blank
- [x] VA0
- [ ] VA0.5
- [ ] VA0.8
- [ ] VA1
The region select screen within the loader shows my BIOS is US_BTR_1.000U941115, I'm guessing this is a VA1 board.

**Console Region**
- [ ] PAL
- [X] NTSC-U
- [ ] NTSC-J
- [ ] Other

**Firmware and Loader Version**
To check your firmware and loader version, go to the Options in the Loader app (Start button). The text next to "FW" is your board's firmware, and the text next to "V" is the Loader version.
- Firmware Version:6cdf9cc3
- Loader Version:2afdf05

**Cartridge Attached**
(Please select more than one if it applies)
- [X] None
- [X] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
1. Launch Game with (A)
2. Skip Konami intro with start, then choose salamander. Choose a 1p game, play until you reach the first boss.
3. Game freezes when voice says "Enemy has penetrated force field", repeating "field" over and over.

1. Launch game with (B) or (C)(with Action Replay Cart inserted)
2. Same as launching game with (A)

**Flex Cable Attached**
- [x] Original Flex Cable
- [X] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
Game should let you fight (and in my case die several times) the first boss and continue on to the 2nd level.
**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

**Additional context**
This seems to be an issue with the Konami deluxe packs, as I've had similar issues with Twinbee Deluxe  Pack, Gradius Deluxe Pack, Parodius Deluxe pack. All freeze at about the end of the first level or beginning of the second level.

**Comment by jpipes** [comment] 2020-07-04 21:48
Tried this with the original flex cable, and had no change. However, I did notice on both cables that the game also crashes in the sound test. I was able to play one song, but the next froze. Probably faster to replicate that way.

I don't have another saturn to test on, so really not sure whether this is an issue with the fenrir, the firmware, or something on my end. 
As it is, some games work flawlessly (Magic knight Rayearth, Night Warriors, Vampire Savior, Earthworm Jim 2, SF Alpha 1 and 2, Saturn Bomberman, Warcraft 2) other games work for a bit, but freeze (The konami deluxe packs, Space Hulk,  capcom generations 1 and 2) and some don't load at all after the sega logo (capcom generations 3, Braindead 13, Street Fighter Alpha 3)

Should I start bug reports for all of these?

**Comment by ThanosSiopoudis** [comment] 2020-07-21 17:47
Fixed in version `da719d1b`

**Comment by jpipes** [comment] 2020-07-25 00:06
With firmware da719d1b, I still have freezing in Salamander Deluxe Pack, at the same place, but sometimes even in the middle of the level.

**Comment by ThanosSiopoudis** [comment] 2020-07-25 11:36
The worst thing with this, is trying to replicate it. The game is HARD! :)
I'll give it a go again now.

**Comment by ThanosSiopoudis** [comment] 2020-07-25 12:06
So @jpipes I'm not able to reproduce this with the latest firmware now.
Can you please try without the AR cart attached and let me know if that works? I'm trying this with an original 4MB Ram cart, or without.

**Comment by jpipes** [comment] 2020-07-26 03:34
OK, heres what I've got. I've tried with two different sd cards, a Samsung 32GB EVO (HCI) and a TOPSEL 32GB (HCIw).
With both cards, I've done a fresh format using Rufus on Windows 10 Home (64 bit)
Rufus settings: FAT32, 16kb clusters.

I tried without the Action Replay cartridge for both direct boot and cd player boot, and then tested with the cart as well.

Both SD cards gave more or less the same results with each option:

1. The FMV that plays after the Konami logo sometimes plays a different video. I'm not sure if this is by design or not. The sound is a bit scratchy only in this section.

2. The music at the game select screen (Salamander, Life Force, Salamander 2) sounds fine, not scratchy at all.

3. Most of the time no music in the level once you start Salamander. I was able to get music once during this last test on my first direct boot on the TOPSEL SD card, but it crashed after I picked up the ripple laser from the last batch of the first wave of enemies. Every other time on both cards, including a direct boot on the same card afterwards, there has been no music once you start the game. Voice and sound effects are unaffected.

4. Game generally crashes as the first boss appears and the "Enemy has penetrated our force field" voice clip is playing. This seems to be where the music would change to the boss theme (if i had music)

5. I'm trying to concentrate on Salamander Deluxe Pack, as I know it a little bit better than the other ones, but with this new firmware, I've also had Gokujou Parodius Da! Deluxe Pack and Gradius Deluxe Pack freeze on me.

**Comment by jpipes** [comment] 2020-07-26 03:43
> The worst thing with this, is trying to replicate it. The game is HARD! :)
> I'll give it a go again now.

LOL At least for the first level the trick is to get as many options (the little round things) as possible and remember if you do get hit, you can pick those back up.

Also, a big thanks for your help!

**Comment by ThanosSiopoudis** [comment] 2020-08-02 19:31
Ok @jpipes, let's reopen the ticket and I'll try to replicate this.
In the meantime, can you grab the Trurip version (ccd/img from Arquivista) and let me know if it behaves the same?

**Comment by jpipes** [comment] 2020-08-03 01:55
Just tried the Trurip version.

Same behavior across all three loading styles (a and b without the action replay inserted).

No music most of the time. Freezes at the first boss while saying "enemy has penetrated our force field"

At this point, if no one else can replicate the issue, I'm inclined to say it lies somewhere in the hardware on my end. I may try to reflow the solder points on the Fenrir at work sometime this week to see if it helps any.

**Comment by ThanosSiopoudis** [comment] 2020-08-04 19:40
That's good to hear you at least figured the problem out. No worries for the chase, we did actually fix a bug with the cue/bin parser due to this!
I would suggest re-capping that power supply. Fenrir would have been fine with the slightly higher +5v voltage supply (the LDO can take up to 15v) so it sounds like something else down the line on the Saturn board didn't like the increased voltage, or possible increased noise on it.

**Closed by ThanosSiopoudis** 2020-08-04 19:40 UTC
Labels: Awaiting Confirmation, Bug

**Comment by jpipes** [comment] 2020-08-04 21:17
Yes, recapping the supply seems to be in the cards for this Saturn. In the meantime, lowering the voltage has made it much more stable. I tried out the other deluxe packs and had a weird music stop/freeze on parodius in the third level, but seems like everything else is much better. Gradius and salamander packs seem to work fine. Most of the other games I had issues with have cleared up as well. I'll update once I get the supply recapped.
